### ISSUE TITLE
Can't use with liquibase cli due to cast exception

### ISSUE THREAD

**Issue by AlEmerich** [mattbertolini/liquibase-slf4j#16]
Hello !

Basically, I have the exact same error as here: [Issue](https://github.com/mattbertolini/liquibase-slf4j/issues/11)

I am trying to run liquibase 4.17.2 as command line, I put in my classpath logback core and classic (1.4.5), slf4j-api (1.7.36) and liquibase-slf4j (4.1.0). 

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Unexpected error running Liquibase: class com.mattbertolini.liquibase.logging.slf4j.Slf4jLogService cannot be cast to class liquibase.logging.core.JavaLogService (com.mattbertolini.liquibase.logging.slf4j.Slf4jLogService and liquibase.logging.core.JavaLogService are in unnamed module of loader java.net.URLClassLoader @6d06d69c)

For more information, please use the --log-level flag
```

The [PR](https://github.com/liquibase/liquibase/issues/1499) which could resolve that issue was not accepted into the main repository because it has been supposedly already corrected by another change, but it is not on my end. Do you have any workaround or way to solve ? Or should I send a new issue on the liquibase repository ?

Feel free to ask for any additional details :)

**Comment by mattbertolini** [comment]
Hi @AlEmerich. Sadly there isn't anything I can do on this end to prevent the cast exception. The only way I know to fix is to modify Liquibase to leverage their `LogService` interface. Based on a quick code search it looks like the usage in `Main` was fixed but not the usage in `LiquibaseCommandLine`. It looks like they are in the process of refactoring the CLI. What does the stacktrace say? Does it point to `LiquibaseCommandLine`? 

Your best bet is to open an issue with the Liquibase repository and have them fix it.

**Comment by AlEmerich** [comment]
Hello @mattbertolini , thanks for your reply !

**Comment by AlEmerich** [comment]
Hello @mattbertolini, thanks for your reply !

Yes, the error is coming from the `LiquibaseCommandLine`. I tried to recompile Liquibase and changing `liquibase-core` jar but without much success...

Actually, it was easier to fork this repository and change the superclass of `Slf4jLogService` to `JavaLogService` instead of `LogService`. Seems wrong to break encapsulation but at least I have some results...

```
Starting Liquibase at 10:57:50 (version 4.17.2 #5255 built at 2022-11-01 18:07+0000)
Liquibase Version: 4.17.2
Liquibase Community 4.17.2 by Liquibase
{"@timestamp":"2022-11-29T09:57:50.886","@version":"1","message":"Set default schema name to public","logger_name":"liquibase.database.core.PostgresDatabase","thread_name":"main","level":"INFO","level_value":20000,"caller_class_name":"com.mattbertolini.liquibase.logging.slf4j.Slf4jLogger","caller_method_name":"info","caller_file_name":"Slf4jLogger.java","caller_line_number":153}
{"@timestamp":"2022-11-29T09:57:50.950","@version":"1","message":"Successfully acquired change log lock","logger_name":"liquibase.lockservice.StandardLockService","thread_name":"main","level":"INFO","level_value":20000,"caller_class_name":"com.mattbertolini.liquibase.logging.slf4j.Slf4jLogger","caller_method_name":"info","caller_file_name":"Slf4jLogger.java","caller_line_number":153}
{"@timestamp":"2022-11-29T09:57:51.105","@version":"1","message":"Reading from public.databasechangelog","logger_name":"liquibase.changelog.StandardChangeLogHistoryService","thread_name":"main","level":"INFO","level_value":20000,"caller_class_name":"com.mattbertolini.liquibase.logging.slf4j.Slf4jLogger","caller_method_name":"info","caller_file_name":"Slf4jLogger.java","caller_line_number":153}
{"@timestamp":"2022-11-29T09:57:51.298","@version":"1","message":"Successfully released change log lock","logger_name":"liquibase.lockservice.StandardLockService","thread_name":"main","level":"INFO","level_value":20000,"caller_class_name":"com.mattbertolini.liquibase.logging.slf4j.Slf4jLogger","caller_method_name":"info","caller_file_name":"Slf4jLogger.java","caller_line_number":153}
Liquibase command 'update' was executed successfully.
```

My remaining problem is the first 3 lines and the last one, which are not logged as I understood by a `LogService` but by a `UIService` (`ConsoleUIService`, actually). I tried to make `Slf4jLogService` implements `UIService` to fool Liquibase but it ignores it, do you have any idea how I could remove completely these remaining lines ?

Thanks for your help !

**Comment by mattbertolini** [comment]
> Actually, it was easier to fork this repository and change the superclass of `Slf4jLogService` to `JavaLogService` instead of `LogService`. Seems wrong to break encapsulation but at least I have some results...

I hope you can understand why I don't think that is a sustainable approach for this library. As you stated it breaks encapsulation and creates a potential maintenance burden keeping up with a specific implementation rather than the interface and abstract parent.

I will file the necessary pull request to fix the cast exception.

> My remaining problem is the first 3 lines and the last one, which are not logged as I understood by a `LogService` but by a `UIService` (`ConsoleUIService`, actually). I tried to make `Slf4jLogService` extends `ConsoleUIService` to fool Liquibase similarly but it ignores it, do you have any idea how I could remove completely these remaining lines ?

I was not aware of the `UIService` until now (admittedly I don't keep too close watch on Liquibase these days). Based on the code they have an implementation designed to log directly to their logger called [`LoggerUIService`](https://github.com/liquibase/liquibase/blob/552665c3fbaaaae4e352378cf21ec2e868da4276/liquibase-core/src/main/java/liquibase/ui/LoggerUIService.java). They purposely don't create the corresponding service loader declaration file which means they rely on the defaults.

https://github.com/liquibase/liquibase/blob/8305293ca12fb2945a4bb80c1a8a5510f563367d/liquibase-cli/src/main/java/liquibase/integration/commandline/LiquibaseCommandLine.java#L583-L593

I don't think you need to create a whole new `UIService` implementation. Creating the service loader declaration file should be enough to make the `LoggerUIService` take over.

I have to think about whether I want to support that directly in this library. The more I read the CLI code the more I understand the Liquibase authors don't want others changing the service implementations and I don't know if I want to fight that battle as it will become a maintenance nightmare for a niche case. The vast majority of the use cases are filled by what I have now. I'll give it some thought and a few hours of experimentation.

**Comment by mattbertolini** [comment]
PR created: https://github.com/liquibase/liquibase/pull/3518

**Comment by mattbertolini** [comment]
Liquibase version 4.19.0 has been released with the above PR included. I am going to close this ticket as the cast exception is now fixed in their code.
