### ISSUE TITLE
issues with setup on liquibase 4.24.0

### ISSUE THREAD

**Issue by hypery2k** [mattbertolini/liquibase-slf4j#18]
I'm trying to configure JSON logging for Liquibase with this:

```
export JAVA_OPTS="-Dlogback.configurationFile=liquibase.logback.xml"
# Run Liquibase update
bin/liquibase update --defaultsFile liquibase.properties --changeLogFile=changelog-master.yaml --classpath "$(printf %s: lib/*.jar)"
```
This entries are in the classpath:
```
  - /opt/liquibase
  - /opt/liquibase/lib/ecs-logging-core-1.5.0.jar
  - /opt/liquibase/lib/liquibase-slf4j-5.0.0.jar
  - /opt/liquibase/lib/logback-classic-1.2.11.jar
  - /opt/liquibase/lib/logback-core-1.2.11.jar
  - /opt/liquibase/lib/logback-ecs-encoder-1.5.0.jar
  - /opt/liquibase/lib/logstash-logback-encoder-7.4.jar
  - /opt/liquibase/lib/slf4j-api-1.7.3.jar
  - /opt/liquibase/lib/slf4j-simple-1.7.3.jar
```

But my logback config is not used. Any ideas?

**Comment by mattbertolini** [comment]
Hi @hypery2k. If memory serves, I don't think Liquiabse allows custom loggers when executing with the CLI. There's some funky stuff going on with their UIService and I don't know of a way to swap that out. Things could have changed since the last time I checked but I'm not sure right now.

I will say that your classpath does have some conflicts though. I would remove the slf4j-simple jar as that can conflict with the logback-classic jar. Try to make sure you only have one slf4j logging implementation on a classpath at any given time.

**Comment by hypery2k** [comment]
thanks for the hint. Actually didn't get the JSON logging working via CLI. Will leave it now to structured loggging
