### ISSUE TITLE
Liquibase-sfl4j does not seem to work with liquibase 3.5.3.  

### ISSUE THREAD

**Issue by janvandeklok** [mattbertolini/liquibase-slf4j#7]
I am running Liquibase-slf4j  with Liquibase3.5.3  in a JBOSS EAP 7.0 server.
After adding the dependency to ma application pom.vl and running my application, Liquibase still is logging everything to stderr.  
From the documentation , adding the dependency is the only thing to do to make it work. Can someone help me finding the problem???

Regards, 
Jan van de Klok

**Comment by mattbertolini** [comment]
I've not used JBoss in many many years so I have no basis to test this problem. If memory serves, newer versions of JBoss have a module system that might complicate the classpath plugin loading system of Liquibase. This is most likely the reason for the problem. The documentation in my README is for a basic Java application setup. I will look to clarify that information in the future.

Since I do not have a JBoss testing environment I cannot debug this problem. If you are feeling adventurous you can build a example project that demonstrates the problem. Then I can take a look. Also, you can try testing it with a older version of Liquibase (like 3.4.x) to see if that works. That will tell you whether or not the problem was introduced in 3.5.x (like a similar problem reported in #6).

My recommendation is to contact Liquibase via the [bug tracker](http://liquibase.jira.com/) or [forums](http://forum.liquibase.org/) about this problem. They might have more experience with the environment than I do. Thanks.

**Comment by mattbertolini** [comment]
Haven't heard back. Closing issue.
